db:
  build: db
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=django

client:
  build: client
  volumes:
    - /srv/client

api:
  build: server
  links:
    - "db:mysqldb"
  volumes:
    - /srv/api

openfoodfacts:
  build: openfoodfacts

ooshop:
  build: ooshop

app:
  build: .
  volumes_from:
    - client
    - api
    - openfoodfacts
    - ooshop
  ports:
    - "1503:8000"
